:Class APLGit2_uc
⍝ User Command class for "APLGit2"
⍝ Kai Jaeger

    ⎕IO←1 ⋄ ⎕ML←1

    ∇ r←List;c;row;table;⎕TRAP;MinimumVersionOfDyalog;AtLeastVersion
      :Access Shared Public
      AtLeastVersion←{⊃⍵≤{⊃⊃(//)⎕VFI ⍵/⍨2>+\⍵='.'}2⊃'.'⎕WG'aplversion'}
     
   ⍝ Everything between "⍝ >>>>> Start*" and "⍝ >>>>> End*" is injected as part of
   ⍝ the build process of the package - don't edit this!
      ⍝ >>>>> StartListInject
MinimumVersionOfDyalog←'18.0'
⍝ Returns a vector of namespaces, one per user command, carrying `Name`, `Desc`, `Group`,
⍝ `Parse` and `_Project`.\\
⍝ `_Project` is 1 for commands that accept the project as an argument; those that do not
⍝ usually accept `-project=` instead.\\
⍝ ATTENTION 1: the table between the two markers is GENERATED by `Admin.UpdateCommandTable`
⍝ as part of `Make`. Do not edit it here - edit the `Desc:`, `Parse:` and `Project:` comments
⍝ in the user command functions themselves, and then run `Make`.\\
⍝ ATTENTION 2: the BODY of this function - everything below the header - is injected into the
⍝ user command script by `InjectListOfObjectsIntoUserCommandScript`. Three consequences:\\
⍝ * It must run without APLGit2 being loaded at all, so it must not call anything.
⍝ * The header goes missing on the way, so `dummy` does not exist over there: never use it.
⍝ * Over there `MinimumVersionOfDyalog` is a VARIABLE, injected as a literal, while here it is
⍝   a function; `AtLeastVersion` is a local dfn there and a function here. Both happen to be
⍝   used in a way that works either way - keep it like that.\\
⍝ `Test_AAA_001` checks that the injected copy still matches this one.
 r←⍬
 table←0 4⍴⊂''
 :If AtLeastVersion⊃(//)⎕VFI MinimumVersionOfDyalog
⍝ >>>>> StartTableInject
     table⍪←'Add' '1 -project=' 0 'Executes the git "Add" command'
     table⍪←'AddGitIgnore' '1s' 0 'Create a file .gitignore, or merge default values with an existing one'
     table⍪←'ChangeLog' '1 -project=' 0 'Takes an APL name and lists all commits the object was part of'
     table⍪←'CloneRepo' '2s -branch= -depth= -dry' 0 'Creates a clone of the given repository'
     table⍪←'Commit' '1s -m= -amend' 1 'Performs a commit on the current branch'
     table⍪←'CompareCommits' '2s -project= -use= -files' 0 'Compares two different commits'
     table⍪←'CompareVersions' '1-2 -project= -use= -files' 0 'Compares two versions of a file or an APL object'
     table⍪←'Diff' '1s -op=all stage work' 1 'Produces a list with changed/deleted/added files by comparing what "op" defines'
     table⍪←'FetchFromIndex' '1s' 1 'Brings back files from the index that were modified or deleted'
     table⍪←'GetLastCommit' '1s -full -branch=' 1 'Returns the latest hash for the current (or the given) branch'
     table⍪←'GetTagOfLatestRelease' '1s -verbose -username=' 1 'Returns the tag of the latest release'
     table⍪←'Init' '1s -quiet' 1 'Initialises a folder for managing it by Git'
     table⍪←'IsDirty' '1s' 1 'Reports whether there are uncommitted changes'
     table⍪←'IsGitProject' '1s' 1 'Returns "yes" or "no" depending on whether there is a ./.git folder'
     table⍪←'ListBranches' '1s -a -r' 1 'Lists all branches for a Git-managed project'
     table⍪←'Log' '2s -verbose -name= -commit=' 1 'Shows the commit logs'
     table⍪←'NoOfUntrackedFiles' '1s' 1 'Returns the number of untracked files'
     table⍪←'OpenGitShell' '1s' 1 'Opens a Git shell for a Git-managed project'
     table⍪←'Push' '1s' 1 'Pushes the current branch after user confirmation'
     table⍪←'RefLog' '1s -max= -all -branch= -project=' 1 'List reference log entries (RefLogs)'
     table⍪←'Repack' '1s -window= -depth=' 1 'Cleans up and optimises Git''s internal storage by consolidating loose objects into packfiles'
     table⍪←'ShowLastVersionInIndex' '1 -project=' 0 'Returns the last version of an APL object or a file in the index'
     table⍪←'Squash' '2s -m=' 1 'Squashes some commits in the current branch into a single one'
     table⍪←'StashApply' '1s -n=' 1 '(Re)-apply stash (by default the last one) to the working area & DO NOT remove from stash stack'
     table⍪←'StashClear' '1s' 1 'Delete all stashes'
     table⍪←'StashDrop' '1s -n=' 1 'Drop latest or given stash'
     table⍪←'StashList' '1s' 1 'List all stashes, if any'
     table⍪←'StashListContent' '2s -noAPLnames' 1 'List all files captured in a stash'
     table⍪←'StashPop' '1s -n=' 1 'Apply a stash to the working area & remove from stash stack, by default the last one'
     table⍪←'StashPush' '999s -m= -u' 1 'Save your local modifications to a new stash entry and roll them back to HEAD (in the working tree and in the index)'
     table⍪←'Status' '1s -verbose -view -noAPLnames' 1 'Reports all untracked files and/or all uncommitted changes'
     table⍪←'Version' '' 0 'Returns the version number as a text vector'
⍝ >>>>> EndTableInject
     :For row :In ⍳≢table
         c←⎕NS''
         c.(Name Parse _Project Desc)←table[row;]
         c.Group←'APLGit2'
         r,←c
     :EndFor
 :EndIf
⍝Done
   ⍝ >>>>> EndListInject
    ∇

    ∇ r←Run(Cmd Args);folder;G;space;ns;noProjectSelected;func;list;ind;msg
      :Access Shared Public
      :If 0=⎕SE.⎕NC'APLGit2'
          {}⎕SE.Tatin.LoadDependencies(⊃⎕NPARTS ##.SourceFile)'⎕SE'
      :EndIf
      G←GetRefToAPLGit2 ⍬
      :If (⊂⎕C Cmd)∊⎕C'Log' 'Squash'
          :If 0≢Args._1
          :AndIf ~⊃⊃⎕VFI Args._1~'-'  ⍝ Neither a positive integer nor "yyyy-mm-dd"
              (r space folder)←G.##.UC.GetSpaceAndFolder Cmd Args
          :Else
              ns←⎕NS''
              ns._1←0
              (r space folder)←G.##.UC.GetSpaceAndFolder Cmd ns
          :EndIf
      :Else
          :If (⊂⎕C Cmd)∊⎕C'AddGitIgnore' 'Add'
          :AndIf ∨/'/\'∊Args._1
              folder←Args._1
              space←''
          :ElseIf ≡/⎕C'StashListContent'Cmd
              :Select ≢Args.Arguments
              :Case 0
                  (space folder)←G.##.EstablishProject''
              :Case 1
                  :If ⊃⊃⎕VFI Args._1
                      (space folder)←G.##.EstablishProject''
                      Args._2←Args._1
                      Args._1←folder
                  :Else
                      (msg space folder)←G.##.UC.GetSpaceAndFolder Cmd Args
                      :If 0<≢msg
                          r←msg ⋄ :Return
                      :EndIf
                  :EndIf
              :Case 2
                  :If ⊃⊃⎕VFI Args._1
                      (space folder)←G.##.EstablishProject Args._2
                      Args._2←Args._1
                      Args._1←folder
                  :Else
                      (msg space folder)←G.##.UC.GetSpaceAndFolder Cmd Args
                      :If 0<≢msg
                          r←msg ⋄ :Return
                      :EndIf
                  :EndIf
              :EndSelect
          :Else
              (r space folder)←G.##.UC.GetSpaceAndFolder Cmd Args
              :If ≡/⎕C'StashPush'Cmd
                  :If 0<≢list←G.##.Status folder
                      list←('D'≠list[;2])⌿list        ⍝ We cannot stash anything deleted from the work tree
                      :If 0=≢''Args.Switch'u'
                          list←('?'≠list[;1])⌿list    ⍝ Remove untracked
                      :EndIf
                      :If 0=≢list
                          r←'No changes found you could stash' ⋄ →0
                      :Else
                          :If (,'?')≡,Args._2
                              ind←'SelectForStash@Select what to stash:' 1 G.##.CommTools.Select list[;3]
                              :If 0=≢ind
                                  r←'Cancelled by user' ⋄ →0
                              :Else
                                  Args._2←list←list[ind;2]
                              :EndIf
                          :Else
                              Args._2←list←list[;3]
                          :EndIf
                      :EndIf
                  :Else
                      r←'No changes found you could stash' ⋄ →0
                  :EndIf
              :EndIf
          :EndIf
      :EndIf
      :If (⊂⎕C Cmd)∊,⊂'version'
      :OrIf ~noProjectSelected←∧/space folder∊''⍬
          func←G.##.UC⍎Cmd
          r←func space folder Args
      :EndIf
    ⍝Done
    ∇

    ∇ r←level Help cmd;ref
      :Access Shared Public
      r←0⍴⊂''
      :If 9=⎕NC'⎕SE.APLGit2'
          ref←GetRefToAPLGit2''
          :If 3=ref.##.⎕NC'UC.Help'
              r←level ref.##.UC.Help cmd
          :Else
              PrintError''
          :EndIf
      :Else
          ⎕←'APLGit2 not found'
      :EndIf
    ∇

    ∇ ref←GetRefToAPLGit2 dummy
    ⍝ Just a cover: the implementation lives in UC.GetRefToAPLGit2, so the two cannot drift
    ⍝ apart. By the time this is called ⎕SE.APLGit2 is there - Run makes sure of it.
      ref←⎕SE.APLGit2.##.UC.GetRefToAPLGit2 dummy
    ∇

    ∇ PrintError dummy;msg
      msg←''
      :If 3=⎕NC'⎕SE.APLGit2.Version'
          msg←' APLGit2 is not installed correctly. Please remove and install again.'
      :EndIf
      ⎕←msg
    ∇

:EndClass
